baseURL = 'https://puttehi.eu'
languageCode = 'en-us'
title = 'puttehi.eu (Petteri Zitting)'
disableKinds = ['taxonomy', 'term']
[markup]
[markup.goldmark]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
#title = true
